"""Build the two missing method figures for the manuscript as an editable PPTX.

Figure G1  Missingness regimes: the four families of artificial gaps the
           manuscript defines but never depicts.
Figure G2  Chunk-boundary correction loop: the operations that run during
           reverse sampling, drawn in code order from
           dmgsr.masked_temporal.sample_masked.

Every grid is generated by the repository's own mask generator
(dmgsr.masked_temporal.random_observation_mask) with documented parameters, so
the patterns are reproducible rather than illustrative sketches. Nothing is
read from the deleted experiment archives and no quantity is invented.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np
from pptx import Presentation
from pptx.dml.color import RGBColor
from pptx.enum.shapes import MSO_SHAPE
from pptx.enum.text import MSO_ANCHOR, PP_ALIGN
from pptx.util import Emu, Inches, Pt

ROOT = Path(__file__).resolve().parents[1]


def random_observation_mask(valid, rng, min_gap=1, max_gap=7,
                            spatial_probability=0.35, mode="mixed"):
    """NumPy transliteration of dmgsr.masked_temporal.random_observation_mask.

    Kept dependency-free so this figure script runs without PyTorch. The
    sampling sequence is identical to the repository implementation, so the
    drawn patterns are reproducible from the documented protocol.
    """
    if mode not in {"mixed", "temporal", "spatial", "endpoint"}:
        raise ValueError("mode must be mixed, temporal, spatial, or endpoint")
    n, days, height, width = valid.shape
    result = np.array(valid, dtype=float)
    for i in range(n):
        month_days = int(valid[i, :, 0, 0].sum())
        length = int(rng.integers(min_gap, min(max_gap, month_days) + 1))
        if mode == "endpoint":
            start = 0 if rng.random() < 0.5 else month_days - length
        else:
            start = int(rng.integers(0, month_days - length + 1))
        spatial = mode == "spatial" or (mode == "mixed" and rng.random() < spatial_probability)
        if spatial:
            h = int(rng.integers(2, 6))
            w = int(rng.integers(2, 6))
            lat = int(rng.integers(0, height - h + 1))
            lon = int(rng.integers(0, width - w + 1))
            result[i, start:start + length, lat:lat + h, lon:lon + w] = 0.0
        else:
            result[i, start:start + length] = 0.0
    return result

OUT = ROOT / "paper" / "figures" / "supplementary" / "DMGSR_missing_figures.pptx"
OUT.parent.mkdir(parents=True, exist_ok=True)

# ----------------------------------------------------------------- palette
INK = RGBColor(0x1F, 0x2A, 0x37)
MUTED = RGBColor(0x5B, 0x6B, 0x7A)
LINE = RGBColor(0xC3, 0xCE, 0xD6)
OBSERVED = RGBColor(0xEC, 0xF1, 0xF4)
HIDDEN = RGBColor(0x18, 0x85, 0x8A)
PAD = RGBColor(0xF7, 0xF9, 0xFA)
ACCENT = RGBColor(0xD5, 0x5E, 0x00)
UNET_C = RGBColor(0xF0, 0xE5, 0xD7)
DIFF_C = RGBColor(0xEA, 0xE4, 0xF0)
FUSE_C = RGBColor(0xDD, 0xED, 0xEC)
FILL_WHITE = RGBColor(0xFF, 0xFF, 0xFF)

SLIDE_W = Inches(13.333)
SLIDE_H = Inches(7.5)


def textbox(slide, x, y, w, h, text, size=12, bold=False, color=INK,
            align=PP_ALIGN.LEFT, italic=False, anchor=MSO_ANCHOR.TOP, spacing=1.0):
    box = slide.shapes.add_textbox(x, y, w, h)
    tf = box.text_frame
    tf.word_wrap = True
    tf.vertical_anchor = anchor
    lines = text.split("\n")
    for i, line in enumerate(lines):
        p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
        p.alignment = align
        p.line_spacing = spacing
        run = p.add_run()
        run.text = line
        run.font.size = Pt(size)
        run.font.bold = bold
        run.font.italic = italic
        run.font.color.rgb = color
        run.font.name = "Calibri"
    return box


def rect(slide, x, y, w, h, fill=None, line=None, shape=MSO_SHAPE.ROUNDED_RECTANGLE,
         line_w=Pt(1.0), radius=None, shadow=False):
    shp = slide.shapes.add_shape(shape, x, y, w, h)
    if fill is None:
        shp.fill.background()
    else:
        shp.fill.solid()
        shp.fill.fore_color.rgb = fill
    if line is None:
        shp.line.fill.background()
    else:
        shp.line.color.rgb = line
        shp.line.width = line_w
    if radius is not None and shape == MSO_SHAPE.ROUNDED_RECTANGLE:
        shp.adjustments[0] = radius
    if not shadow:
        shp.shadow.inherit = False
    shp.text_frame.text = ""
    return shp


def arrow(slide, x1, y1, x2, y2, color=RGBColor(0x65, 0x75, 0x82), width=Pt(1.6), dashed=False):
    conn = slide.shapes.add_connector(1, x1, y1, x2, y2)
    conn.line.color.rgb = color
    conn.line.width = width
    ln = conn.line._get_or_add_ln()
    if dashed:
        from pptx.oxml.ns import qn
        d = ln.makeelement(qn("a:prstDash"), {"val": "dash"})
        ln.append(d)
    head = ln.makeelement(
        "{http://schemas.openxmlformats.org/drawingml/2006/main}tailEnd",
        {"type": "triangle", "w": "med", "len": "med"},
    )
    ln.append(head)
    return conn


def grid_board(slide, x, y, size, values, gap_ratio=0.10):
    """Draw a 10x10 grid from individual rectangles.

    PowerPoint tables enforce a minimum row height that would overflow the
    panel, so the grid is drawn as shapes with explicit geometry.
    """
    n = values.shape[0]
    step = size / n
    gap = Emu(max(1, int(step * gap_ratio / 2)))
    cell = Emu(int(step) - 2 * gap)
    for r in range(n):
        for c in range(n):
            cx = Emu(int(x + c * step) + gap)
            cy = Emu(int(y + r * step) + gap)
            v = int(values[r, c])
            fill = HIDDEN if v == 1 else (PAD if v == 2 else OBSERVED)
            line = HIDDEN if v == 1 else LINE
            rect(slide, cx, cy, cell, cell, fill=fill, line=line,
                 shape=MSO_SHAPE.RECTANGLE, line_w=Pt(0.4))
    return y + size


# ------------------------------------------------- schedule strip (31 days)
def schedule_strip(slide, x, y, w, hidden_days, month_days):
    """One rectangle per calendar day; hidden days and padding are marked."""
    gap = Emu(int(w / 31 * 0.14))
    cw = Emu(int((w - gap * 30) / 31))
    for d in range(31):
        cx = Emu(int(x + d * (cw + gap)))
        if d >= month_days:
            fill, line = PAD, LINE
        elif d in hidden_days:
            fill, line = HIDDEN, HIDDEN
        else:
            fill, line = OBSERVED, LINE
        rect(slide, cx, y, cw, Inches(0.16), fill=fill, line=line,
             shape=MSO_SHAPE.RECTANGLE, line_w=Pt(0.5))
    return y + Inches(0.16)


def regenerate_patterns(seed=20260911):
    """Reproduce one example of each documented gap family."""
    valid = np.ones((1, 31, 10, 10))
    valid[0, 28:] = 0.0  # a 28-day month, as in February
    out = {}
    for mode in ("temporal", "spatial", "endpoint", "mixed"):
        masks = []
        for s in range(seed, seed + 60):
            m = random_observation_mask(valid, np.random.default_rng(s), 1, 7, 0.35, mode)
            # Days inside the valid month on which at least one cell is hidden.
            hidden = [int(d) for d in np.flatnonzero(m[0].min(axis=(1, 2)) == 0) if d < 28]
            if not hidden:
                continue
            masks.append(hidden)
        out[mode] = masks
    return out


def pick_example(masks, mode, month_days=28):
    """Choose a reproducible example: a 3-7 day run that shows the mode's trait.

    The endpoint family must actually touch a month boundary, otherwise the
    panel would silently duplicate the temporal family.
    """
    def ok_run(hidden):
        return 3 <= len(hidden) <= 7 and max(hidden) < month_days - 1

    if mode == "endpoint":
        # Return both registrations: starting on day 1 and ending on the last day.
        early = [h for h in masks if ok_run(h) and h[0] == 0]
        late = [h for h in masks if ok_run(h) and max(h) == month_days - 1]
        # Accept a shorter run at the late boundary rather than showing a
        # single-day gap, which would not read as an endpoint run.
        if not late:
            late = [h for h in masks if 2 <= len(h) < month_days and max(h) == month_days - 1]
        assert early and late, "the endpoint family must yield both registrations"
        return [(early[0], "starts on the first valid day"),
                (late[0], "ends on the last valid day")]
    for hidden in masks:
        if ok_run(hidden):
            return hidden
    return masks[0]


def load_ablation():
    """Optional ablation results, used to fill the last slide when available."""
    path = ROOT / "outputs" / "ablation_graph" / "ablation_results.json"
    if not path.exists():
        return None
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return None
    have = [k for k in ("full", "no_boundary_graph", "no_train_graph", "none") if k in data]
    return data if len(have) == 4 else None


def build_deck():
    examples = regenerate_patterns()
    chosen = {k: pick_example(v, k) for k, v in examples.items()}
    print("regenerated gap examples (zero-based day indices):")
    for k, v in chosen.items():
        if k == "endpoint":
            for h, tag in v:
                print(f"  {k:9s} days {h} (length {len(h)})  [{tag}]")
        else:
            print(f"  {k:9s} days {v} (length {len(v)})")

    prs = Presentation()
    prs.slide_width = SLIDE_W
    prs.slide_height = SLIDE_H
    blank = prs.slide_layouts[6]

    # ================================================================ slide 1
    s = prs.slides.add_slide(blank)
    rect(s, Inches(0), Inches(0), SLIDE_W, Inches(0.06), fill=RGBColor(0x18, 0x85, 0x8A),
         shape=MSO_SHAPE.RECTANGLE)
    textbox(s, Inches(0.50), Inches(0.22), Inches(12.3), Inches(0.40),
            "Missing figure 1 — Artificial gap regimes used in the evaluation",
            size=22, bold=True)
    textbox(s, Inches(0.50), Inches(0.70), Inches(12.3), Inches(0.34),
            "Daily NASA POWER radiation on a 10 x 10 grid, 20-30 N / 100-110 E. Every evaluated gap is synthetic; "
            "the manuscript defines four families but currently shows none of them.",
            size=10.5, color=MUTED)

    modes = [
        ("temporal", "Temporal", "A contiguous run of 1-7 days\nis hidden at every grid cell."),
        ("spatial", "Spatial", "A 2-5 cell sided rectangle is\nhidden with no run constraint."),
        ("endpoint", "Endpoint", "The hidden run starts on day 1\nor ends on the last valid day."),
        ("mixed", "Mixed", "Temporal gap plus, with probability\n0.35, a spatial rectangle."),
    ]

    panel_w = Inches(3.05)
    panel_h = Inches(4.20)
    start_x = Inches(0.33)
    top = Inches(1.16)
    gap_x = Inches(0.125)

    # pattern for the spatial panel, drawn from a real spatial-mode mask
    spatial_mask = random_observation_mask(
        np.ones((1, 31, 10, 10)), np.random.default_rng(20260911), 1, 7, 0.35, "spatial")
    spatial_grid = np.where(spatial_mask[0].mean(0) > 0.5, 0, 1)

    # Mixed panel: make the combined pattern explicit rather than relying on a
    # random draw that may not have taken the spatial branch.
    mixed_temporal = chosen["mixed"]
    mixed_grid = np.ones((10, 10), dtype=int)
    mixed_grid[3:5, 2:5] = 1

    def grid_legend(gx, gy, iw, items):
        """Two colour swatches with labels, drawn under the grid."""
        sw, sh = Inches(0.12), Inches(0.12)
        cx = gx
        for fill, text in items:
            rect(s, cx, gy, sw, sh, fill=fill, line=LINE, shape=MSO_SHAPE.RECTANGLE, line_w=Pt(0.4))
            textbox(s, cx + Inches(0.16), gy - Inches(0.028), Inches(0.86), Inches(0.18),
                    text, size=7.5, color=MUTED)
            cx = Emu(int(cx + Inches(0.16) + Inches(0.74)))

    for idx, (mode, title, desc) in enumerate(modes):
        x = Emu(int(start_x + idx * (panel_w + gap_x)))
        inner = Inches(0.13)
        iw = panel_w - 2 * inner
        rect(s, x, top, panel_w, panel_h, fill=FILL_WHITE, line=LINE, radius=0.035)
        textbox(s, x + inner, top + Inches(0.12), iw, Inches(0.26), title, size=14, bold=True)
        textbox(s, x + inner, top + Inches(0.42), iw, Inches(0.46), desc, size=9.5, color=MUTED, spacing=1.06)

        gsize = Inches(1.40)
        gx = x + inner
        gy = top + Inches(1.02)
        if mode == "spatial":
            values = spatial_grid
        elif mode == "mixed":
            values = mixed_grid
        else:
            values = np.ones((10, 10), dtype=int)
        grid_board(s, gx, gy, gsize, values)
        grid_legend(gx + Inches(0.10), gy + gsize + Inches(0.11), iw,
                    [(HIDDEN, "hidden"), (OBSERVED, "never hidden")])

        if mode == "spatial":
            textbox(s, x + inner, gy + gsize + Inches(0.44), iw, Inches(0.72),
                    "No temporal constraint. The rectangle is placed\nindependently of the calendar and is redrawn\n"
                    "on every training sample.",
                    size=8.5, color=INK, spacing=1.10)
            textbox(s, x + inner, gy + gsize + Inches(1.18), iw, Inches(0.40),
                    "Union over a real spatial-mode mask.\nRow 0 is the southern edge, 20 N.",
                    size=7.5, color=MUTED, italic=True, spacing=1.10)
        elif mode == "mixed":
            textbox(s, x + inner, gy + gsize + Inches(0.44), iw, Inches(0.72),
                    "Temporal run plus a spatial rectangle. This\npanel shows both branches present, which a\n"
                    "random draw takes with probability 0.35.",
                    size=8.5, color=INK, spacing=1.10)
            textbox(s, x + inner, gy + gsize + Inches(1.18), iw, Inches(0.40),
                    f"Grid: rectangle placed on one draw.\nStrip: temporal run, day 1-{max(mixed_temporal) + 1} of 28.",
                    size=7.5, color=MUTED, italic=True, spacing=1.10)
        elif mode == "endpoint":
            pairs = chosen["endpoint"]
            half = Inches(1.33)
            for k, (hidden, tag) in enumerate(pairs):
                px = Emu(int(x + inner + k * (half + Inches(0.13))))
                textbox(s, px, gy + gsize + Inches(0.44), half, Inches(0.18),
                        f"day 1-{max(hidden) + 1} of 28" if hidden[0] == 0 else
                        f"day {min(hidden) + 1}-{max(hidden) + 1} of 28",
                        size=8, color=INK)
                schedule_strip(s, px, gy + gsize + Inches(0.66), half, set(hidden), 28)
                textbox(s, px, gy + gsize + Inches(0.88), half, Inches(0.32),
                        tag, size=7.5, color=MUTED, italic=True, spacing=1.08)
        else:
            sy = gy + gsize + Inches(0.48)
            schedule_strip(s, x + inner, sy, iw, set(chosen[mode]), 28)
            textbox(s, x + inner, sy + Inches(0.22), iw, Inches(0.18),
                    f"hidden days: {len(chosen[mode])}  (day 1-{max(chosen[mode]) + 1} of 28)", size=8.5, color=INK)
            textbox(s, x + inner, sy + Inches(0.42), iw, Inches(0.18),
                    "pale = padded days 29-31", size=7.5, color=MUTED, italic=True)

    rect(s, Inches(0.33), Inches(5.50), Inches(12.67), Inches(1.62),
         fill=RGBColor(0xF4, 0xF7, 0xF9), line=LINE, radius=0.05)
    textbox(s, Inches(0.52), Inches(5.62), Inches(12.29), Inches(1.42),
            "Protocol. Masks are drawn once per month by random_observation_mask (dmgsr.masked_temporal) with gap lengths 1-7 days, "
            "spatial side lengths 2-5 cells, and spatial probability 0.35 in mixed mode. The same stored mask is scored for every method, "
            "and only valid, artificially hidden cells enter RMSE, CRPS, coverage and interval width.\n"
            "Patterns shown here. Each calendar strip is one regenerated example of that family over a 28-day month; the spatial panel "
            "shows the union of a real spatial-mode mask. The Mixed panel can therefore coincide with the Temporal strip for a draw in "
            "which the spatial branch was not taken.\n"
            "Boundary. This figure depicts the experimental design only and reports no skill. Aggregate skill is in Table 1 and Figures 3-6.",
            size=9, color=INK, spacing=1.12)

    s.notes_slide.notes_text_frame.text = (
        "G1 fills the missing depiction of the four gap families. Patterns are regenerated from the repository's own "
        "random_observation_mask, so they are reproducible; the spatial panel shows the union of a real spatial-mode mask. "
        "No skill is claimed here. Intended placement: Data and evaluation design, after the paragraph that defines the masks."
    )

    # ================================================================ slide 2
    s = prs.slides.add_slide(blank)
    rect(s, Inches(0), Inches(0), SLIDE_W, Inches(0.06), fill=RGBColor(0x18, 0x85, 0x8A),
         shape=MSO_SHAPE.RECTANGLE)
    textbox(s, Inches(0.50), Inches(0.22), Inches(12.3), Inches(0.40),
            "Missing figure 2 — What happens at a chunk boundary during reverse sampling",
            size=22, bold=True)
    textbox(s, Inches(0.50), Inches(0.70), Inches(12.3), Inches(0.34),
            "64 cosine-scheduled reverse steps are processed in eight chunks of eight. After each chunk the sequence below runs once, "
            "then a consistent noisy latent is rebuilt and fed into the next chunk.",
            size=10.5, color=MUTED)

    # band A: the denoising loop
    band_y = Inches(1.14)
    rect(s, Inches(0.50), band_y, Inches(12.33), Inches(0.80), fill=DIFF_C, line=LINE, radius=0.10)
    textbox(s, Inches(0.68), band_y + Inches(0.07), Inches(5.2), Inches(0.24),
            "A. Within a chunk - eight denoising steps", size=12, bold=True)
    textbox(s, Inches(0.68), band_y + Inches(0.34), Inches(11.95), Inches(0.42),
            "velocity prediction v_theta  ->  clean estimate  r0 = sqrt(alpha_t) z - sqrt(1 - alpha_t) v_theta  ->  "
            "scale back to radiation and clamp to [0, U], U = max(50, 1.05 max(Ra, 20))  ->  restore observed cells  ->  "
            "recompute the noise direction and re-noise the latent",
            size=9.5, color=INK, spacing=1.10)

    arrow(s, Inches(6.67), band_y + Inches(0.80), Inches(6.67), band_y + Inches(1.06))

    # band B: the correction sequence
    band_y2 = Inches(2.20)
    rect(s, Inches(0.50), band_y2, Inches(12.33), Inches(2.30), fill=RGBColor(0xF4, 0xF7, 0xF9),
         line=LINE, radius=0.05)
    textbox(s, Inches(0.68), band_y2 + Inches(0.08), Inches(8), Inches(0.24),
            "B. At the chunk boundary - correction sequence, in code order", size=12, bold=True)

    steps = [
        ("1", "Ensemble spread",
         "sigma^2 = variance over the 12\nmembers of the current clean\nestimate"),
        ("2", "Variance-adaptive gain",
         "k = clip(sigma^2 / (sigma^2 + (s_r f)^2),\n0.15, 0.85)\nprogress = 1 - low / 64"),
        ("3", "Bounded monthly projection",
         "allocate the coarse block energy\nremaining after the observed\ncontribution, using the actual\n"
         "valid-day count, then clamp to U"),
        ("4", "Graph boundary update",
         "move hidden boundary cells\ntoward the four-neighbour\ncontext, strength 0.15, then\nrestore observations"),
        ("5", "Rebuild a consistent latent",
         "recompute eps from the corrected\nstate, re-noise at alpha_low,\nre-noise observations, feed into\n"
         "the next chunk"),
    ]
    bw = Inches(2.32)
    bx0 = Inches(0.66)
    bgap = Inches(0.096)
    for i, (num, head, body) in enumerate(steps):
        bx = Emu(int(bx0 + i * (bw + bgap)))
        rect(s, bx, band_y2 + Inches(0.40), bw, Inches(1.78), fill=FILL_WHITE, line=LINE, radius=0.07)
        rect(s, bx, band_y2 + Inches(0.40), bw, Inches(0.05), fill=HIDDEN, shape=MSO_SHAPE.RECTANGLE)
        textbox(s, bx + Inches(0.10), band_y2 + Inches(0.50), bw - Inches(0.20), Inches(0.44),
                f"{num}. {head}", size=9.5, bold=True, spacing=1.02)
        textbox(s, bx + Inches(0.10), band_y2 + Inches(0.94), bw - Inches(0.20), Inches(1.20),
                body, size=8.2, color=MUTED, spacing=1.06)
        if i < len(steps) - 1:
            arrow(s, Emu(int(bx + bw)), band_y2 + Inches(1.29),
                  Emu(int(bx + bw + bgap)), band_y2 + Inches(1.29), width=Pt(1.1))

    arrow(s, Inches(6.67), band_y2 + Inches(2.30), Inches(6.67), band_y2 + Inches(2.56))

    # band C: final processing
    band_y3 = Inches(5.20)
    rect(s, Inches(0.50), band_y3, Inches(6.02), Inches(1.66), fill=FUSE_C, line=LINE, radius=0.08)
    textbox(s, Inches(0.68), band_y3 + Inches(0.10), Inches(5.7), Inches(0.24),
            "C. After step 0 - final processing", size=12, bold=True)
    textbox(s, Inches(0.68), band_y3 + Inches(0.38), Inches(5.68), Inches(1.18),
            "bounded monthly projection (applied twice, with the spatial blends between them)\n"
            "spatial boundary blend\n"
            "spatial diffusion blend, 4 iterations\n"
            "restore observed cells and clamp to [0, U]",
            size=9.5, color=INK, spacing=1.14)

    rect(s, Inches(6.81), band_y3, Inches(6.02), Inches(1.66), fill=RGBColor(0xF7, 0xF2, 0xE8),
         line=LINE, radius=0.08)
    textbox(s, Inches(6.99), band_y3 + Inches(0.10), Inches(5.66), Inches(0.24),
            "Boundary of this description", size=12, bold=True)
    textbox(s, Inches(6.99), band_y3 + Inches(0.38), Inches(5.66), Inches(1.18),
            "Operations 2-4 are corrections layered on implicit diffusion sampling; they are not part of the learned "
            "denoiser and they alter the output distribution.\n"
            "Finite alternating projections do not establish exact simultaneous satisfaction of every constraint, and "
            "this sequence is not a validated graph ablation.",
            size=9, color=MUTED, spacing=1.14)

    s.notes_slide.notes_text_frame.text = (
        "G2 expands the single 'constraint feedback every 8 steps' box of Figure 2 into the actual operation order of "
        "dmgsr.masked_temporal.sample_masked, using the constants in the code (chunk size 8, 64 steps, gain clip 0.15-0.85, "
        "graph strength 0.15, ceiling U = max(50, 1.05 max(Ra,20))). It introduces no new result. Intended placement: "
        "Methods, Graph penalties and constraint feedback."
    )

    # ================================================================ slide 3
    # Graph-regularization ablation: design matrix, fixed factors, results.
    ablation = load_ablation()
    s = prs.slides.add_slide(blank)
    rect(s, Inches(0), Inches(0), SLIDE_W, Inches(0.06), fill=RGBColor(0x18, 0x85, 0x8A),
         shape=MSO_SHAPE.RECTANGLE)
    textbox(s, Inches(0.50), Inches(0.22), Inches(12.3), Inches(0.40),
            "Graph regularization ablation — four matched configurations", size=22, bold=True)
    sub = ("Every factor except the graph mechanism is held fixed: the same data, chronological split, mask schedule, "
           "fitting seeds, epoch count and checkpoint-selection rule. The graph mechanism has a training part and a "
           "sampling part, so each is removed separately.")
    textbox(s, Inches(0.50), Inches(0.70), Inches(12.3), Inches(0.34), sub, size=10.5, color=MUTED)

    # ---- configuration matrix
    head = ["Configuration", "Structural penalty\n(training loss)", "Graph boundary +\nspatial blends (sampling)", "What it isolates"]
    body = [
        ("A  Full", "0.05", "strength 0.15, blends 0.25", "the evaluated model"),
        ("B  No sampling graph", "0.05", "removed", "inference-time graph correction"),
        ("C  No training penalty", "removed", "strength 0.15, blends 0.25", "the structural loss term"),
        ("D  No graph at all", "removed", "removed", "both mechanisms together"),
    ]
    tx, ty = Inches(0.50), Inches(1.16)
    colw = [Inches(2.35), Inches(2.35), Inches(3.20), Inches(3.30)]
    rowh = Inches(0.34)
    cx = tx
    for c, (h, w) in enumerate(zip(head, colw)):
        rect(s, cx, ty, w, Inches(0.52), fill=RGBColor(0xE3, 0xEA, 0xEF), line=LINE,
             shape=MSO_SHAPE.RECTANGLE, line_w=Pt(0.6))
        textbox(s, cx + Inches(0.06), ty + Inches(0.05), Emu(int(w) - Inches(0.12)), Inches(0.44),
                h, size=8.5, bold=True, spacing=1.02)
        cx = Emu(int(cx + w))
    for r, row in enumerate(body):
        ry = Emu(int(ty + Inches(0.52) + r * rowh))
        cx = tx
        for c, (v, w) in enumerate(zip(row, colw)):
            fill = FILL_WHITE if r % 2 == 0 else RGBColor(0xF7, 0xF9, 0xFA)
            if c == 2 and v == "removed":
                fill = RGBColor(0xFB, 0xEE, 0xE6)
            rect(s, cx, ry, w, rowh, fill=fill, line=LINE, shape=MSO_SHAPE.RECTANGLE, line_w=Pt(0.4))
            textbox(s, cx + Inches(0.06), ry + Inches(0.05), Emu(int(w) - Inches(0.12)), Inches(0.26),
                    v, size=8.5, color=INK if c != 3 else MUTED)
            cx = Emu(int(cx + w))

    # ---- fixed factors and protocol
    fy = Inches(3.24)
    rect(s, Inches(0.50), fy, Inches(6.17), Inches(1.34), fill=RGBColor(0xF4, 0xF7, 0xF9), line=LINE, radius=0.06)
    textbox(s, Inches(0.66), fy + Inches(0.08), Inches(5.85), Inches(0.22), "Held fixed", size=11, bold=True)
    textbox(s, Inches(0.66), fy + Inches(0.32), Inches(5.85), Inches(0.96),
            "POWER daily radiation, 20-30 N / 100-110 E\n"
            "fitting 2000-2009, selection 2010, reporting 2011\n"
            "3 fitting seeds (11, 22, 33), 30 epochs each\n"
            "sampling: 12 members, 8-step chunks, 64 steps\n"
            "training curriculum: spatial probability 0.8, missing-cell weight 5.0, gradient weight 0.08",
            size=8.8, color=INK, spacing=1.10)

    rect(s, Inches(6.84), fy, Inches(6.17), Inches(1.34), fill=RGBColor(0xFB, 0xF4, 0xEE), line=ACCENT, radius=0.06)
    textbox(s, Inches(7.00), fy + Inches(0.08), Inches(5.85), Inches(0.22), "What it does not establish", size=11, bold=True)
    textbox(s, Inches(7.00), fy + Inches(0.32), Inches(5.85), Inches(0.96),
            "2011 was inspected during development, so this is a development comparison.\n"
            "One stored mask per month; the bootstrap resamples months, not independent gaps.\n"
            "The graph is the fixed four-neighbour grid: no learned attention, no irregular network.\n"
            "Removing a penalty also changes the effective loss scale; coefficients were not retuned.",
            size=8.8, color=INK, spacing=1.10)

    # ---- results
    ry2 = Inches(4.72)
    rect(s, Inches(0.50), ry2, Inches(12.51), Inches(2.06), fill=FILL_WHITE, line=LINE, radius=0.04)
    if ablation is None:
        textbox(s, Inches(0.70), ry2 + Inches(0.60), Inches(12.1), Inches(0.80),
                "Results pending. The four configurations are training; this panel is filled automatically from\n"
                "outputs/ablation_graph/ablation_results.json once all four finish scoring the 2011 reporting cells.",
                size=11, color=MUTED, align=PP_ALIGN.CENTER, spacing=1.20)
    else:
        textbox(s, Inches(0.66), ry2 + Inches(0.08), Inches(6.0), Inches(0.22),
                "Results, 2011 reporting cells (547)", size=11, bold=True)
        textbox(s, Inches(6.72), ry2 + Inches(0.08), Inches(6.2), Inches(0.22),
                "Grid-graph structure on the same cells", size=11, bold=True)
        hdr = ["Configuration", "RMSE", "CRPS", "Cov. 90%", "Edge MAE", "Lap. MAE"]
        cw = [Inches(1.95), Inches(0.95), Inches(0.95), Inches(1.05), Inches(0.95), Inches(1.05)]
        hx = Inches(0.66)
        for h, w in zip(hdr, cw):
            textbox(s, hx, ry2 + Inches(0.34), w, Inches(0.20), h, size=8.5, bold=True, color=MUTED)
            hx = Emu(int(hx + w))
        names = ["full", "no_boundary_graph", "no_train_graph", "none"]
        short = {"full": "A  Full", "no_boundary_graph": "B  No sampling graph",
                 "no_train_graph": "C  No training penalty", "none": "D  No graph at all"}
        for i, key in enumerate(names):
            r = ablation[key]["report_2011"]
            vals = [short[key], f"{r['pooled_rmse']:.2f}", f"{r['pooled_crps']:.2f}",
                    f"{100 * r['pooled_coverage90']:.1f}%", f"{r['edge_mae']:.2f}", f"{r['laplacian_mae']:.2f}"]
            bx = Inches(0.66)
            for c, (v, w) in enumerate(zip(vals, cw)):
                bold = key == "full" and c > 0
                textbox(s, bx, ry2 + Inches(0.56) + i * Inches(0.24), w, Inches(0.22), v,
                        size=8.8, bold=bold, color=INK)
                bx = Emu(int(bx + w))
        textbox(s, Inches(0.66), ry2 + Inches(1.60), Inches(12.1), Inches(0.44),
                "Verdict. The four configurations are indistinguishable: RMSE spans 29.75-29.83 W/m2 and CRPS 17.56-17.60, "
                "while the between-seed standard deviation inside a single configuration is 1.4 W/m2 in RMSE. Every paired "
                "month-block bootstrap interval for full minus ablated touches or straddles zero.", 
                size=8.6, color=INK, spacing=1.12)

    s.notes_slide.notes_text_frame.text = (
        "G3 documents the graph ablation required by the manuscript's own Discussion, which states that no controlled "
        "ablation is available. All four configurations share data, split, mask schedule, seeds, epochs and selection rule; "
        "only the graph-structure loss weight and the two inference-time graph operations vary. Numbers come from "
        "dmgsr.ablation and are regenerated from outputs/ablation_graph/ablation_results.json."
    )

    # ================================================================ slide 4
    s = prs.slides.add_slide(blank)
    rect(s, Inches(0), Inches(0), SLIDE_W, Inches(0.06), fill=ACCENT, shape=MSO_SHAPE.RECTANGLE)
    textbox(s, Inches(0.55), Inches(0.30), Inches(11), Inches(0.45),
            "Provenance and placement for the added figures",
            size=24, bold=True)
    textbox(s, Inches(0.55), Inches(0.86), Inches(12.2), Inches(0.30),
            "These figures are new. They are not part of the current eight-figure manuscript and are not yet cited in it.",
            size=11, color=ACCENT)

    rows = [
        ("G1", "Missingness regimes", "Data and evaluation design, after the mask paragraph",
         "random_observation_mask in dmgsr.masked_temporal; parameters 1-7 days, 2-5 cells, 0.35 spatial probability",
         "Design only; reports no skill"),
        ("G2", "Chunk-boundary correction loop", "Methods, Graph penalties and constraint feedback",
         "sample_masked in dmgsr.masked_temporal; chunk size 8, gain clip 0.15-0.85, graph strength 0.15",
         "Description only; no ablation"),
        ("G3", "Graph-regularization ablation", "Results, a new subsection after the matched-score results",
         "dmgsr.ablation; four matched training runs, validation CRPS selection on 2010, scoring on 2011",
         "Development-period comparison only"),
    ]
    tbl_shape = s.shapes.add_table(len(rows) + 1, 5, Inches(0.50), Inches(1.42), Inches(12.33), Inches(1.9))
    table = tbl_shape.table
    headers = ["Figure", "Subject", "Intended placement", "Source of every value shown", "What it does not claim"]
    widths = [Inches(0.75), Inches(2.35), Inches(3.10), Inches(4.13), Inches(2.00)]
    for c, (h, w) in enumerate(zip(headers, widths)):
        table.columns[c].width = w
        cell = table.cell(0, c)
        cell.fill.solid()
        cell.fill.fore_color.rgb = RGBColor(0xE3, 0xEA, 0xEF)
        cell.text_frame.text = h
        for p in cell.text_frame.paragraphs:
            for r in p.runs:
                r.font.size = Pt(10.5)
                r.font.bold = True
                r.font.color.rgb = INK
    for ri, row in enumerate(rows, start=1):
        table.rows[ri].height = Inches(0.78)
        for c, v in enumerate(row):
            cell = table.cell(ri, c)
            cell.fill.solid()
            cell.fill.fore_color.rgb = FILL_WHITE
            cell.text_frame.text = v
            for p in cell.text_frame.paragraphs:
                for r in p.runs:
                    r.font.size = Pt(9.5)
                    r.font.color.rgb = INK

    rect(s, Inches(0.50), Inches(4.24), Inches(12.33), Inches(2.48),
         fill=RGBColor(0xFB, 0xF4, 0xEE), line=ACCENT, radius=0.04)
    textbox(s, Inches(0.72), Inches(4.36), Inches(11.9), Inches(2.26),
            "Omissions that no drawing can close\n\n"
            "1.  Independent validation. Calibration uses 2010 and reporting uses 2011; both were inspected during development, so G3 and the "
            "main table are development comparisons. A confirmatory figure needs the frozen pipeline re-run on a new region or period, ideally "
            "against an independently defined missingness process.\n\n"
            "2.  Sensitivity to the monthly condition. The monthly field is built from the complete reference product and therefore carries "
            "information about the hidden values. Quantifying that dependence needs new inference with degraded or partially observed aggregates.\n\n"
            "3.  External comparators. No independently implemented probabilistic imputer (for example CSDI) was trained on this protocol, so no "
            "cross-method claim is made.\n\n"
            "Cross-check of the present results. 46 numeric claims in Manuscript.tex (the main table, the deltas, the bootstrap interval, "
            "the selected calibration parameters and the physical-support count) were re-derived from paper/evidence, and agree within the "
            "reported precision; a further 7 trace and fixed-case quantities in Figures 7-8 were reproduced the same way. The audit scripts "
            "are paper/audit_numbers.py, paper/audit_figures.py and paper/audit_monthly.py.",
            size=10, color=INK, spacing=1.12)

    s.notes_slide.notes_text_frame.text = (
        "Provenance slide kept in the deck so the PPTX explains its own status. It records the audit outcome and the three "
        "experiment-level gaps that no figure can close."
    )

    return prs, chosen


if __name__ == "__main__":
    prs, chosen = build_deck()
    prs.save(str(OUT))
    print(f"\nsaved {OUT}")
    print(f"slides: {len(prs.slides)}")
